# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0004_auto_20170925_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='auth',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
